#!/usr/bin/env python3
"""env-overlay.py BASE OVERLAY OUT — write OUT = BASE with OVERLAY's keys replaced.

For kits that read ONE env file (MiaAI's DS4 DSpark reads .env.dspark, or
ENV_FILE when set): the 3-node lane runs from a generated copy, so the live
2-node file stays the single source of truth and nothing drifts. Every active
`KEY=` line for an overlay key is rewritten in place (so no earlier line can
win and no later one can override it); keys BASE lacks are appended. Comments
and blank lines in OVERLAY are ignored. OUT is mode 600 (the file carries API
keys) and starts with a do-not-edit banner.
"""
import os
import re
import sys

base, overlay, out = sys.argv[1:4]
want = {}
for line in open(overlay):
    s = line.strip()
    if not s or s.startswith("#"):
        continue
    key, _, val = s.partition("=")
    want[key.strip()] = val
seen = set()
lines = []
for line in open(base):
    m = re.match(r"^(\s*(?:export\s+)?)([A-Za-z_][A-Za-z0-9_]*)=", line)
    if m and m.group(2) in want:
        k = m.group(2)
        # marker on its own line: docker compose also parses this file as an env_file
        lines.append(f"# env-overlay: {k} from {os.path.basename(overlay)}\n{m.group(1)}{k}={want[k]}\n")
        seen.add(k)
    else:
        lines.append(line)
extra = [k for k in want if k not in seen]
if extra:
    lines.append(f"\n# --- appended by env-overlay from {os.path.basename(overlay)} ---\n")
    lines += [f"{k}={want[k]}\n" for k in extra]
banner = (f"# GENERATED by sparkrun-recipes/tools/env-overlay.py from {base}\n"
          f"# + {overlay}. Do not edit: change those two and re-run the make target.\n")
fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, "w") as f:
    f.write(banner + "".join(lines))
os.chmod(out, 0o600)
print(f"env-overlay: {out} ({len(seen)} replaced, {len(extra)} appended)")
